service: baselog

provider:
  name: aws
  runtime: nodejs16.x

  stage: dev
  region: us-east-1

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  funcDir: src/modules

functions:
  signup:
    handler: ${self:custom.funcDir}/authentication/framework/functions/sign-up.handler
    environment:
      DYNAMODB_ACCOUNTS: ${ssm:baselog-${self:custom.stage}-dynamodb-accounts-table}
      EMAIL_INDEX: ${ssm:baselog-${self:custom.stage}-email-index}
    events:
      - http:
          path: /authentication/signup
          method: POST
