service: baselog

provider:
  name: aws
  runtime: nodejs16.x

  stage: dev
  region: us-east-1

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  funcDir: src/modules

functions:
  - ${file(${self:custom.funcDir}/authentication/framework/functions/sign-in/_handler.yml)}
  - ${file(${self:custom.funcDir}/authentication/framework/functions/sign-up/_handler.yml)}
  - ${file(${self:custom.funcDir}/catalog/framework/functions/create-product/_handler.yml)}
